export const NEW_EXPENSES_REQUEST = "NEW_EXPENSES_REQUEST";
export const NEW_EXPENSES_SUCCESS = "NEW_EXPENSES_SUCCESS";
export const NEW_EXPENSES_RESET = "NEW_EXPENSES_RESET";
export const NEW_EXPENSES_FAIL = "NEW_EXPENSES_FAIL";

export const ADMIN_EXPENSES_REQUEST = "ADMIN_EXPENSES_REQUEST";
export const ADMIN_EXPENSES_SUCCESS = "ADMIN_EXPENSES_SUCCESS";
export const ADMIN_EXPENSES_FAIL = "ADMIN_EXPENSES_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";